graph TD;
N0["source"]
N1["source_item"]
N0 --> N1
N2["func_definition"]
N1 --> N2
N3["def"]
N2 --> N3
N4["func_signature"]
N2 --> N4
N5["identifier: main"]
N4 --> N5
N6["("]
N4 --> N6
N7[")"]
N4 --> N7
N8["of"]
N4 --> N8
N9["type_ref"]
N4 --> N9
N10["builtin_type"]
N9 --> N10
N11["int"]
N10 --> N11
N12["statement"]
N2 --> N12
N13["expression_statement"]
N12 --> N13
N14["expr"]
N13 --> N14
N15["binary_expr"]
N14 --> N15
N16["expr"]
N15 --> N16
N17["identifier: i"]
N16 --> N17
N18["="]
N15 --> N18
N19["expr"]
N15 --> N19
N20["literal"]
N19 --> N20
N21["dec: 1"]
N20 --> N21
N22[";"]
N13 --> N22
N23["statement"]
N2 --> N23
N24["loop_statement"]
N23 --> N24
N25["while"]
N24 --> N25
N26["expr"]
N24 --> N26
N27["binary_expr"]
N26 --> N27
N28["expr"]
N27 --> N28
N29["identifier: i"]
N28 --> N29
N30["<"]
N27 --> N30
N31["expr"]
N27 --> N31
N32["literal"]
N31 --> N32
N33["dec: 5"]
N32 --> N33
N34["statement"]
N24 --> N34
N35["block_statement"]
N34 --> N35
N36["{"]
N35 --> N36
N37["statement"]
N35 --> N37
N38["expression_statement"]
N37 --> N38
N39["expr"]
N38 --> N39
N40["binary_expr"]
N39 --> N40
N41["expr"]
N40 --> N41
N42["identifier: i"]
N41 --> N42
N43["="]
N40 --> N43
N44["expr"]
N40 --> N44
N45["binary_expr"]
N44 --> N45
N46["expr"]
N45 --> N46
N47["identifier: i"]
N46 --> N47
N48["+"]
N45 --> N48
N49["expr"]
N45 --> N49
N50["literal"]
N49 --> N50
N51["dec: 1"]
N50 --> N51
N52[";"]
N38 --> N52
N53["}"]
N35 --> N53
N54["loop_end"]
N24 --> N54
N55["statement"]
N2 --> N55
N56["return_statement"]
N55 --> N56
N57["return"]
N56 --> N57
N58["expr"]
N56 --> N58
N59["identifier: i"]
N58 --> N59
N60[";"]
N56 --> N60
N61["end"]
N2 --> N61
