graph TD;
N0["source"]
N1["comment"]
N0 --> N1
N2["source_item"]
N0 --> N2
N3["func_definition"]
N2 --> N3
N4["def"]
N3 --> N4
N5["func_signature"]
N3 --> N5
N6["identifier: square"]
N5 --> N6
N7["("]
N5 --> N7
N8["list_arg"]
N5 --> N8
N9["arg"]
N8 --> N9
N10["identifier: x"]
N9 --> N10
N11["of"]
N9 --> N11
N12["type_ref"]
N9 --> N12
N13["builtin_type"]
N12 --> N13
N14["int"]
N13 --> N14
N15[")"]
N5 --> N15
N16["of"]
N5 --> N16
N17["type_ref"]
N5 --> N17
N18["builtin_type"]
N17 --> N18
N19["int"]
N18 --> N19
N20["statement"]
N3 --> N20
N21["return_statement"]
N20 --> N21
N22["return"]
N21 --> N22
N23["expr"]
N21 --> N23
N24["binary_expr"]
N23 --> N24
N25["expr"]
N24 --> N25
N26["identifier: x"]
N25 --> N26
N27["*"]
N24 --> N27
N28["expr"]
N24 --> N28
N29["identifier: x"]
N28 --> N29
N30[";"]
N21 --> N30
N31["end"]
N3 --> N31
N32["source_item"]
N0 --> N32
N33["func_definition"]
N32 --> N33
N34["def"]
N33 --> N34
N35["func_signature"]
N33 --> N35
N36["identifier: main"]
N35 --> N36
N37["("]
N35 --> N37
N38[")"]
N35 --> N38
N39["of"]
N35 --> N39
N40["type_ref"]
N35 --> N40
N41["builtin_type"]
N40 --> N41
N42["int"]
N41 --> N42
N43["statement"]
N33 --> N43
N44["expression_statement"]
N43 --> N44
N45["expr"]
N44 --> N45
N46["binary_expr"]
N45 --> N46
N47["expr"]
N46 --> N47
N48["identifier: i"]
N47 --> N48
N49["="]
N46 --> N49
N50["expr"]
N46 --> N50
N51["literal"]
N50 --> N51
N52["dec: 1"]
N51 --> N52
N53[";"]
N44 --> N53
N54["statement"]
N33 --> N54
N55["loop_statement"]
N54 --> N55
N56["while"]
N55 --> N56
N57["expr"]
N55 --> N57
N58["binary_expr"]
N57 --> N58
N59["expr"]
N58 --> N59
N60["identifier: i"]
N59 --> N60
N61["<"]
N58 --> N61
N62["expr"]
N58 --> N62
N63["literal"]
N62 --> N63
N64["dec: 5"]
N63 --> N64
N65["statement"]
N55 --> N65
N66["block_statement"]
N65 --> N66
N67["{"]
N66 --> N67
N68["statement"]
N66 --> N68
N69["expression_statement"]
N68 --> N69
N70["expr"]
N69 --> N70
N71["binary_expr"]
N70 --> N71
N72["expr"]
N71 --> N72
N73["identifier: i"]
N72 --> N73
N74["="]
N71 --> N74
N75["expr"]
N71 --> N75
N76["binary_expr"]
N75 --> N76
N77["expr"]
N76 --> N77
N78["identifier: i"]
N77 --> N78
N79["+"]
N76 --> N79
N80["expr"]
N76 --> N80
N81["literal"]
N80 --> N81
N82["dec: 1"]
N81 --> N82
N83[";"]
N69 --> N83
N84["}"]
N66 --> N84
N85["loop_end"]
N55 --> N85
N86["statement"]
N33 --> N86
N87["expression_statement"]
N86 --> N87
N88["expr"]
N87 --> N88
N89["binary_expr"]
N88 --> N89
N90["expr"]
N89 --> N90
N91["identifier: y"]
N90 --> N91
N92["="]
N89 --> N92
N93["expr"]
N89 --> N93
N94["call_expr"]
N93 --> N94
N95["expr"]
N94 --> N95
N96["identifier: square"]
N95 --> N96
N97["("]
N94 --> N97
N98["list_expr"]
N94 --> N98
N99["expr"]
N98 --> N99
N100["literal"]
N99 --> N100
N101["dec: 2"]
N100 --> N101
N102[")"]
N94 --> N102
N103[";"]
N87 --> N103
N104["statement"]
N33 --> N104
N105["return_statement"]
N104 --> N105
N106["return"]
N105 --> N106
N107["expr"]
N105 --> N107
N108["identifier: i"]
N107 --> N108
N109[";"]
N105 --> N109
N110["end"]
N33 --> N110
